// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHa5WqKm8Q_o8NCdRGKI8hkTSIPHrsLKk',
    appId: '1:196820092488:web:9c44080126cefa95efba7d',
    messagingSenderId: '196820092488',
    projectId: 'crafty-bay-project',
    authDomain: 'crafty-bay-project.firebaseapp.com',
    storageBucket: 'crafty-bay-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYoe2UGtwLMjl5-Qb7januska8rZTZUY',
    appId: '1:196820092488:android:d1a7cabcef1a8920efba7d',
    messagingSenderId: '196820092488',
    projectId: 'crafty-bay-project',
    storageBucket: 'crafty-bay-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdx6B_9mXtDkel7KJ9dUTWycwEh9vUFfA',
    appId: '1:196820092488:ios:cd26488bd827dbbdefba7d',
    messagingSenderId: '196820092488',
    projectId: 'crafty-bay-project',
    storageBucket: 'crafty-bay-project.firebasestorage.app',
    iosBundleId: 'com.example.craftyBayProject',
  );
}
